---
title: "Iteration and list cols"
author: "Zeqi Li"
date: "2024-10-29"
output: github_document
---
```{r setup, include=FALSE}
library(rvest)
library(tidyverse)
```


## Lists
```{r}
l = list(vec_numeric = 1:4,
         unif_sample = runif(100),
         mat = matrix(1:8,
                      nrow = 2,
                      ncol = 4,
                      byrow = TRUE),
         summary = summary(rnorm(1000)))

l$mat
l[["mat"]]
l[["mat"]][1, 3]
l[[4]]
```

```{r}
list_norm = list(a = rnorm(20, 0, 5),
                 b = rnorm(20, 4, 5),
                 c = rnorm(20, 0, 10),
                 d = rnorm(20, 4, 10))

list_norm[["a"]]
```


Reusing the the `mean_and_sd` function
```{r}
mean_and_sd = function(x) {
  
  mean_x = mean(x)
  sd_x = sd(x)

  out_df = tibble(mean = mean_x, 
                  sd = sd_x)
  
  return(out_df)
}
```

```{r}
mean_and_sd(list_norm[["a"]])
mean_and_sd(list_norm[["b"]])
mean_and_sd(list_norm[["c"]])
mean_and_sd(list_norm[["d"]])
```

## `for` loop
```{r, message = FALSE}
output = vector("list", length = 4)

for (i in 1:4){
  output[[i]] = mean_and_sd(list_norm[[i]])
}

output
```


## `map`
```{r}
output_map = map(list_norm, mean_and_sd)
```

other functions with `map`
```{r}
output = map(list_norm, mean_and_sd) |> 
  bind_rows()

map_dfr(list_norm, median)

map_dbl(list_norm, IQR)
```

## list columns
```{r}
listcol_df = tibble(name = c("a", "b", "c", "d"),
                    samp = list_norm)

listcol_df |> 
  filter(name %in% c("a", "b"))

listcol_df |> 
  select(-samp)

listcol_df[["samp"]][["a"]]
```
```{r}
mean_and_sd(listcol_df[["samp"]][["a"]])
mean_and_sd(listcol_df[["samp"]][["b"]])

map(listcol_df[["samp"]], mean_and_sd)
```

adding list columns
```{r}
listcol_df |> 
  mutate(output = map(samp, mean_and_sd))

listcol_df |> 
  mutate(output = map(samp, mean_and_sd),
         iqr = map(samp, IQR)) |> 
  select(-samp) |> 
  unnest(output)
```

## NSDUH
```{r}
nsduh_table_format = function(html, table_num) {
  
  out_table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value"))
    
  return(out_table)
}
```

Importing the html
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

nsduh_table_format(html = nsduh_html, table_num = 1)
nsduh_table_format(html = nsduh_html, table_num = 4)
nsduh_table_format(html = nsduh_html, table_num = 5)
```
### Learning assessment
```{r}
listcol_df = tibble(
  drug = c("marj", "cocaine", "heroin"),
  table_n = c(1, 4, 5)) |> 
  mutate(table = map(table_n, nsduh_table_format, html = nsduh_html)) |> 
  unnest(table)


listcol_df = tibble(
  drug = c("marj", "cocaine", "heroin"),
  table_n = c(1, 4, 5)) |> 
  mutate(table = map(table_n, \(x) nsduh_table_format(html = nsduh_html,
                                                      table_num = x))) |> 
  unnest(table)
```


## NYNOAA
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_nest = weather_df |> 
  nest(data = date:tmin)
```


regression
```{r}
lm(tmax ~ tmin, data = weather_nest[["data"]][[1]])
lm(tmax ~ tmin, data = weather_nest[["data"]][[2]])
lm(tmax ~ tmin, data = weather_nest[["data"]][[3]])
```
```{r}
weather_nest |> 
  mutate(model_fit = map(data, \(x) lm(tmax ~ tmin, data = x)))
```

